### ISSUE TITLE
run time error on diffusers 0.21.4

### ISSUE THREAD

**Issue by bemova** [Kihensarn/TI-Guided-Edit#2]
TypeError: forward() got an unexpected keyword argument 'scale'

python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 2227, in forward
hidden_states = resnet(hidden_states, temb, scale=lora_scale)

could you please share the correct version of the diffusers you have used?

This error happens when running:
I tested the code with diffusers 0.21.4 and the latest version of diffusers.
sh scripts/run_app.sh

**Comment by Kihensarn** [comment]
Sorry for the bug, maybe diffusers 0.15.0 can solve this error.

**Comment by bemova** [comment]
The latest version that can solve the problem is 0.20.2.
Thanks!
